### ISSUE TITLE
translation error 

### ISSUE THREAD

**Issue by dixiAI** [beltransen/velo2cam_calibration#24]
Hello!
have someone some experiences with the calibration results?. In the simulation I get big errors in the z axis and/or in the y axis from 2 cm to 10 cm. It have realized they depend of the position of the calibration target or the position between the sensors.
Do you get gut results? I mean calibration errors under 1 cm?
Thank you very much in advance for your help and comments
cheers
Dixie

**Comment by beltransen** [comment]
The reported results correspond to very different calibration scenarios. as described in the paper. We performed experiments in a variety of relative positions between the sensors and the calibration target in order to test the robustness of the method against challenging calibration configurations. We have also received feedback from other users that have used this method to calibrate the sensors of their own vehicles with successful results. 

It looks a little bit weird to get these errors while working in a simulated environment. Have you double-checked that the parameters are properly adjusted?

**Comment by cguindel** [comment]
We are closing this issue because it has been inactive for two months, and no further information has been provided.

**Comment by iyuner** [comment]
Hello I also met such problem- translation error is big and rotation is fairly good in the simulation. @dixiAI did you solve it in the end?
