### ISSUE TITLE
Cnfiguration with other stereo camera

### ISSUE THREAD

**Issue by minaameli** [beltransen/velo2cam_calibration#26]
Hello, 
Thanks for the package.

Regarding the configuration, since I couldn't find any documentation, I'd like to know that what are the necessary update in order to use this package with any camera?

Except updating the topics based on our stereo camera and marker info, what else needs to be configured?

I applied the mentioned changes and couldn't see the results in publishing topics!

Thank you in advance.

**Comment by cguindel** [comment]
Hi @minaameli. Sorry for the late reply.

In principle, the only change required to run the method on your own camera is the name of the topics, as you already mentioned. I guess you already know, but the nodes in `stereo_pattern.launch` make use of the topics `stereo_camera/left/image_rect_color` and `stereo_camera/right/image_rect_color`. If your camera is under another namespace, please make sure to replace every appearance of `stereo_camera` in that launchfile by your camera's name, including the one in the group tag: `<group ns="stereo_camera">` You can use _rqt_graph_ to check if everything is correctly connected.

Apart from that, you will probably need to tune some parameters used by the different steps of the algorithm to adapt them to your device. Perhaps the most important ones are the thresholds of the pass-through filters, that can be modified dynamically using _rqt_reconfigure_. You need to make the calibration marker visible in the filtered stereo cloud so that the method can work properly. We are working on several ways to simplify the configuration of these parameters, so please stay tuned.

Once you run your camera driver and `roslaunch velo2cam_calibration stereo_pattern.launch`, you should be able to see some PointCloud2 topics resulting from the different steps of the procedure (e.g., `disparity` and `edge_z_filtered_cloud`). Otherwise, it would be a good idea to check at what point in the pipeline the processing is stopped.

Let us know if you can make it work!
