### ISSUE TITLE
Issues with stereo_pattern.launch

### ISSUE THREAD

**Issue by Mikor-mkr** [beltransen/velo2cam_calibration#32]
Hello !

For starters I want to thank you for this calibration package, and I want to mention an issue I have because I can not get my head around what might be the source of the problem. I am using the T265 camera which I've set the image topics as following:

```
T265/left/camera_info
T265/left/image_rect_gray
T265/right/camera_info
T265/right/image_rect_gray
```
I've modified the first lines of the launch file as following:

```
  <arg name="stdout" default="screen" />
  <arg name="camera_name" default="/T265" />
  <arg name="image_topic" default="image_rect_gray" />
  <arg name="frame_name" default="T265" />
  <arg name="sensor_id" default="0" />
```
But when I am launching the file it seems to be stuck at the /extract_circle_indices nodelet as this point I get the warning: This node/nodelet subscribes topics only when subscribed. But my guess is that this happens because the topic `/T265/z_filtered_cloud` is empty. And it seems that all this come back to the stereo manager because the topics `/T265/points2` and `/T265/disparity` are empty, any ideas what to do to fix this ?

Note: At the rqt_graph the /T265/stereo_manager_0 seems to be connected with the topics coming from the T265 left & right.

**Comment by cguindel** [comment]
Hi @Mikor-mkr,

According to what you report, it seems that the problem is in the construction of the disparity map and the stereo cloud. Note that those steps are carried out by standard [stereo_image_proc](http://wiki.ros.org/stereo_image_proc) nodelets, in particular, `stereo_image_proc/disparity` and `stereo_image_proc/point_cloud2` nodelets. 

We don't have access to a T265 camera, so we can't troubleshoot the problem properly. However, you might want to check the stereo_image_proc documentation; maybe the stereo matching implemented by that package is not suitable for your camera. If that is the case, you can also generate a `T265/disparity` topic containing a disparity map from an external source (e.g., the camera driver) and remove the `stereo_image_proc/disparity` nodelet from `stereo_pattern.launch`.

 I hope this helps you to solve the issue.
