### ISSUE TITLE
Calibration results are of very low quality

### ISSUE THREAD

**Issue by alasdairhunter** [beltransen/velo2cam_calibration#49]
I am trying to calibrate a rgb monocular camera and a velodyne vlp32 camera. I have followed the instructions on the github, and everything works well as far as I can tell, but the output is basically just nonsense. 
The camera is located directly beneath the lidar with a vertical displacement of about 10 cm, but the calibration results vary a lot whenever the target is moved, and none of the results are good. I am talking about displacements of well over 20 cm.
I dont have any idea why this should be. Has anyone else encountered very poor results, then realized it was do to a specific parameter?
Range filtered cloud:
![Screenshot from 2022-06-21 15-23-28](https://user-images.githubusercontent.com/23552984/174731635-4f649aa3-1b78-476b-b782-992671f8b775.png)
XYZ filtered cloud:
![Screenshot from 2022-06-21 15-23-25](https://user-images.githubusercontent.com/23552984/174731697-29fd268d-f200-4e85-997e-c55062a40a64.png)
Camera:
![Screenshot from 2022-06-21 15-31-36](https://user-images.githubusercontent.com/23552984/174731754-f32027f6-45e1-4918-ad33-32d097bf4e28.png)

**Comment by Mkarasneh** [comment]
Hello @alasdairhunter, I am also trying to calibrate a monocular camera with the velodyne VLP 32. However, I didn't figure out how to visualize the output as in the last picture in your question, can you share with me how you obtained that output?

**Comment by cguindel** [comment]
@alasdairhunter We have never observed such a large error in our tests. I guess the problem is related to your specific configuration, but I can give you some advice to troubleshoot the issue:
- Have you tried using more than one pattern pose (M>1)?
- Are the intrinsic parameters of your fish-eye camera properly calibrated?
- As it seems that you have already activated the DEBUG mode, could you look at the _cumulative_cloud_ topics in RVIZ? They contain the center locations of the pattern circles in both modalities, so they should look like this:

![image](https://user-images.githubusercontent.com/15200248/174822299-2cc3efce-ff48-4c72-b5da-e1c187a01b08.png)

@Mkarasneh You can obtain that visualization by setting the DEBUG flag to 1 [here](https://github.com/beltransen/velo2cam_calibration/blob/bfba57837e1efd979f8514512756b450f921e2aa/include/velo2cam_utils.h#L30).

**Comment by alasdairhunter** [comment]
Thanks for your response @cguindel:
1) Yes I usually try 3 poses.
2) I think the fisheye distortion is partly responsible. I have upgraded from Ros melodic to noetic so that I can rectify the fish eye image and broadcast that instead (with distortion coeffients then set to 0). I'll let you know how it goes.
3) I'll include a screenshot of the center after I have rerun it.

**Comment by alasdairhunter** [comment]
@Mkarasneh set DEBUG to 1 in include/velo2cam_utils.h

**Comment by lbouz102** [comment]
@alasdairhunter Did you change tune any parameters besides pass_through_radius_[min/max] and pass_through_[x,y,z]_[min/max]? My zyx and range filtered clouds look similar to yours but I'm having the issue described in #51

**Comment by cguindel** [comment]
Closing the issue due to inactivity. Feel free to reopen it if you need.
